#!/usr/bin/env bash
# lib/repo.sh — 仓库与 machine 解析(require_openbmc_repo/write_source_manifest). 术语见 CONTEXT.md source manifest.
# Exit: direct-exit module（非 leaf-pure, 使用 exit-code 契约值 0/1/2/3）.


read_source_label() {
    local label=""
    if [[ -f "$SOURCE_MANIFEST_FILE" ]]; then
        label=$(read_manifest_field source_label 2>/dev/null || true)
        label=$(trim_whitespace "$label")
    fi
    if [[ -z "$label" ]]; then
        label="community"
    fi
    echo "$label"
}

is_valid_repo_url() {
    local repo_url="$1"
    [[ "$repo_url" =~ ^https?:// ]] || [[ "$repo_url" =~ ^ssh:// ]] || [[ "$repo_url" =~ ^git:// ]] || [[ "$repo_url" =~ ^git@ ]]
}

# detect_runtime_git_host — 提取 runtime Git mirror host(术语见 CONTEXT.md)。
# vendor 脚本(meta-*/git-mirror-url.sh, legacy github-gitlab-url.sh)的 GIT_MIRROR_HOST/GITLAB_IP 优先;
# fallback 主仓 origin(git remote get-url)。带一次性全局缓存——clone_sub_repos 遍历 ~570 个 dep repo,
# 每个 ${GITLAB_IP} clone_url 都会触发解析,不缓存会重算 N 次。leaf-pure:绝不 exit;
# 拿到/拿不到 host 都 return 0,不报错(配置缺失由调用者决定 remedy)。
# 调用约定:生产调用必须 direct call(detect_runtime_git_host >/dev/null; x=${_RUNTIME_GIT_HOST:-}),
# 因 $() subshell 不穿透全局缓存;echo 仅供测试/一次性捕获。Returns: echo host 或空串,恒 return 0。
detect_runtime_git_host() {
    # 一次性缓存:哨兵变量区分"已求值(值为空)"与"未求值",不用 -n(host 可合法为空)
    if [[ -n "${_RUNTIME_GIT_HOST_RESOLVED+x}" ]]; then
        echo "${_RUNTIME_GIT_HOST:-}"
        return 0
    fi

    # 本地化 OPENBMC_DIR(nounset 自洽):未设/未初始化时 graceful 返回空,不依赖调用者保证
    local openbmc_dir="${OPENBMC_DIR:-}"
    local host=""
    local _rt_script=""
    local _candidate
    if [[ -n "$openbmc_dir" ]]; then
        for _candidate in "$openbmc_dir"/meta-*/git-mirror-url.sh \
                          "$openbmc_dir"/meta-*/github-gitlab-url.sh; do
            [[ -f "$_candidate" ]] && { _rt_script="$_candidate"; break; }
        done
    fi
    if [[ -f "$_rt_script" ]]; then
        host=$(grep -oP '^(GITLAB_IP|GIT_MIRROR_HOST)=["'"'"']?\K[^"'"'"'\s]+' "$_rt_script" 2>/dev/null | head -1 || true)
    fi

    # fallback: 主仓 origin(git 官方 API,比手解 .git/config 文件更稳健)
    if [[ -z "$host" && -n "$openbmc_dir" ]]; then
        local _remote_url=""
        _remote_url=$(git -C "$openbmc_dir" remote get-url origin 2>/dev/null || true)
        if [[ "$_remote_url" == git@* ]]; then
            host=$(printf '%s\n' "$_remote_url" | sed -E 's/^git@([^:]+):.*/\1/')
        elif [[ "$_remote_url" == http://* || "$_remote_url" == https://* ]]; then
            host=$(printf '%s\n' "$_remote_url" | sed -E 's#^https?://([^/:]+).*#\1#')
        fi
    fi

    _RUNTIME_GIT_HOST="$host"
    _RUNTIME_GIT_HOST_RESOLVED=1
    echo "$host"
    return 0
}

normalize_repo_url() {
    local repo_url="$1"
    local normalized="$repo_url"
    local host=""
    local path=""

    normalized="${normalized#https://}"
    normalized="${normalized#http://}"
    normalized="${normalized#ssh://}"
    normalized="${normalized#git://}"

    if [[ "$normalized" =~ ^([^@]+)@([^:]+):(.+)$ ]]; then
        host="${BASH_REMATCH[2]}"
        path="${BASH_REMATCH[3]}"
        if [[ "$path" =~ ^([0-9]+)/(.*)$ ]]; then
            normalized="$host/${path#*/}"
        else
            normalized="$host/$path"
        fi
    elif [[ "$normalized" =~ ^([^@]+)@(.+)$ ]]; then
        normalized="${BASH_REMATCH[2]}"
    fi

    if [[ "$normalized" =~ ^\[?([^]/:]+)\]?:(.+)$ ]]; then
        host="${BASH_REMATCH[1]}"
        path="${BASH_REMATCH[2]}"
        if [[ "$path" =~ ^([0-9]+)/(.*)$ ]]; then
            normalized="$host/${path#*/}"
        else
            normalized="$host/$path"
        fi
    fi

    normalized="${normalized%/}"
    normalized="${normalized%.git}"

    if [[ "$normalized" =~ ^([^/]+)/(.*)$ ]]; then
        local host="${BASH_REMATCH[1]}"
        local path="${BASH_REMATCH[2]}"
        host="${host,,}"
        path="${path,,}"
        normalized="$host/$path"
    else
        normalized="${normalized,,}"
    fi

    echo "$normalized"
}

derive_source_label() {
    local normalized

    normalized="$(normalize_repo_url "$OPENBMC_REPO_URL")"
    if [[ "$normalized" == "github.com/openbmc/openbmc" ]]; then
        SOURCE_LABEL="community"
    else
        SOURCE_LABEL="custom"
    fi
}

write_source_manifest() {
    local normalized_source
    local timestamp
    local tmp

    normalized_source="$(normalize_repo_url "$OPENBMC_REPO_URL")"
    timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    derive_source_label

    if [[ "$DRY_RUN" -eq 1 ]]; then
        info "[DRY-RUN] Would write source manifest to $SOURCE_MANIFEST_FILE"
        info "[DRY-RUN]   normalized_source=$normalized_source"
        info "[DRY-RUN]   origin_url=$OPENBMC_REPO_URL"
        info "[DRY-RUN]   source_label=$SOURCE_LABEL"
        return 0
    fi

    mkdir -p "$CONFIGS_DIR"
    tmp=$(mktemp "$CONFIGS_DIR/openbmc-source.manifest.XXXXXX") || return 1

    cat > "$tmp" <<EOF
# openbmc source manifest — auto-generated by 'ob init', do not edit by hand
normalized_source=$normalized_source
origin_url=$OPENBMC_REPO_URL
source_label=$SOURCE_LABEL
created_at=$timestamp
EOF

    if ! mv "$tmp" "$SOURCE_MANIFEST_FILE"; then
        rm -f "$tmp"
        return 1
    fi
}

ensure_bootstrap_local_conf() {
    local local_conf="$BUILD_DIR/conf/local.conf"

    require_path "$local_conf" "local.conf" "Run 'ob init' first." 3

    # Detect GitLab IP for recipes that use ${GITLAB_IP} in SRC_URI(via runtime Git mirror host).
    # direct call:函数内全局缓存不穿透 $() subshell(clone_sub_repos 循环复用同一缓存)。
    local gitlab_ip=""
    detect_runtime_git_host >/dev/null
    gitlab_ip="${_RUNTIME_GIT_HOST:-}"

    # If the remote uses SSH, but recipes reference the host via protocol=https,
    # configure git to rewrite HTTPS URLs to SSH automatically.
    # This handles GitLab servers where HTTPS is unavailable or requires auth
    # that isn't configured in recipes, while SSH key access works out of the box.
    # Only set when missing — user can override manually if needed.
    if [[ -n "$gitlab_ip" ]]; then
        local _existing_rewrite=""
        _existing_rewrite=$(git config --global --get "url.git@${gitlab_ip}:.insteadOf" 2>/dev/null || true)
        if [[ -z "$_existing_rewrite" ]]; then
            git config --global "url.git@${gitlab_ip}:.insteadOf" "https://${gitlab_ip}/"
            info "Configured git insteadOf: https://${gitlab_ip}/ → git@${gitlab_ip} (SSH rewrite for recipe fetches)"
        else
            verbose "Git insteadOf for ${gitlab_ip} already configured: ${_existing_rewrite} → git@${gitlab_ip}:"
        fi
    fi

    # Add include to local.conf if not already present.
    # The .inc file (managed by generate_build_config) contains all ob init settings.
    local include_line="include externalsrc-$MACHINE.inc"

    if grep -qF "$include_line" "$local_conf"; then
        verbose "Include line already exists in local.conf, skipping."
    else
        cp "$local_conf" "${local_conf}.bak.$(date +%Y%m%d%H%M%S)"
        echo "" >> "$local_conf"
        echo "$include_line" >> "$local_conf"
        info "Added '$include_line' to local.conf"
    fi

    verbose "Ensured ob init local.conf settings in $local_conf"
}

verify_source() {
    local lock_source=""
    local current_origin=""
    local current_source=""
    local requested_url="$OPENBMC_REPO_URL"
    local requested_source=""
    local lock_label=""

    if [[ ! -d "$OPENBMC_DIR/.git" ]]; then
        return 0
    fi

    if [[ ! -f "$SOURCE_MANIFEST_FILE" ]]; then
        current_origin=$(git -C "$OPENBMC_DIR" remote get-url origin 2>/dev/null || true)
        if [[ -n "$current_origin" ]]; then
            OPENBMC_REPO_URL="$current_origin"
            SOURCE_LABEL=""
            write_source_manifest
            if [[ -n "$requested_url" ]]; then
                requested_source=$(normalize_repo_url "$requested_url")
                current_source=$(normalize_repo_url "$current_origin")
                if [[ "$requested_source" != "$current_source" ]]; then
                    error "OpenBMC main repository source conflict detected."
                    error "  Current harness source: $current_source"
                    error "  Requested source:       $requested_source"
                    error "A harness may only bind to one OpenBMC main repository source."
                    error "To use a different source, copy ob-harness and run ob init in the new copy."
                    exit 1
                fi
            fi
            OPENBMC_REPO_URL="$requested_url"
        else
            warn "OpenBMC main repository exists but has no origin remote; skipping source lock bootstrap."
        fi
        return 0
    fi

    lock_source=$(read_manifest_field normalized_source || true)
    lock_label=$(read_manifest_field source_label || true)
    current_origin=$(git -C "$OPENBMC_DIR" remote get-url origin 2>/dev/null || true)

    if [[ -n "$current_origin" ]]; then
        current_source=$(normalize_repo_url "$current_origin")
        if [[ -n "$lock_source" ]] && [[ "$current_source" != "$lock_source" ]]; then
            error "OpenBMC main repository source does not match the source manifest."
            error "  Bound source:   $lock_source"
            error "  Actual origin:  $current_source"
            error "Existing openbmc origin and source manifest have drifted, likely due to a manual change."
            error "Please verify the main repository source before continuing. If you need a different source, use a separate harness copy."
            exit 1
        fi
    else
        warn "OpenBMC main repository has no origin remote; skipping lock vs origin verification."
    fi

    if [[ -n "$OPENBMC_REPO_URL" ]]; then
        requested_source=$(normalize_repo_url "$OPENBMC_REPO_URL")
        if [[ -n "$lock_source" ]] && [[ "$requested_source" != "$lock_source" ]]; then
            error "OpenBMC main repository source conflict detected."
            error "  Current harness source: $lock_source${lock_label:+  ($lock_label)}"
            error "  Requested source:       $requested_source"
            error "A harness may only bind to one OpenBMC main repository source."
            error "To use a different source, copy ob-harness and run ob init in the new copy."
            exit 1
        fi
    fi

    return 0
}

select_openbmc_repo_url() {
    if [[ -n "$OPENBMC_REPO_URL" ]]; then
        if ! is_valid_repo_url "$OPENBMC_REPO_URL"; then
            error "Invalid OpenBMC repository URL: $OPENBMC_REPO_URL"
            error "Supported formats: https://, http://, ssh://, git://, git@"
            error "Provide a valid repository URL via --url <url> or OB_OPENBMC_URL, then retry."
            exit 3
        fi
        return 0
    fi

    if [[ -n "${OB_OPENBMC_URL:-}" ]]; then
        OPENBMC_REPO_URL="$OB_OPENBMC_URL"
        if ! is_valid_repo_url "$OPENBMC_REPO_URL"; then
            error "Invalid OpenBMC repository URL from OB_OPENBMC_URL: $OPENBMC_REPO_URL"
            error "Set OB_OPENBMC_URL to a valid URL, or rerun 'ob init' interactively."
            exit 3
        fi
        return 0
    fi

    while true; do
        echo ""
        echo "Select the OpenBMC source repository:"
        echo "  1) Community (https://github.com/openbmc/openbmc.git)"
        echo "  2) Custom repository URL"
        echo "  Q) Quit source selection (q/Q)"
        if ! read -r -p "$(echo -e "${PROMPT_PREFIX} Choose [1/2/Q]: ")" selection; then
            error "Unable to read repository source selection from stdin."
            error "Use --url <url> or set OB_OPENBMC_URL in non-interactive mode."
            exit 3
        fi

        case "$selection" in
            1)
                OPENBMC_REPO_URL="$DEFAULT_OPENBMC_REPO_URL"
                SOURCE_LABEL="community"
                return 0
                ;;
            2)
                if ! read -r -p "$(echo -e "${PROMPT_PREFIX} Enter the full repository URL: ")" OPENBMC_REPO_URL; then
                    error "Unable to read custom repository URL from stdin."
                    error "Use --url <url> or set OB_OPENBMC_URL in non-interactive mode."
                    exit 3
                fi
                if [[ -z "$OPENBMC_REPO_URL" ]]; then
                    info "Returning to source selection."
                    continue
                fi
                if is_valid_repo_url "$OPENBMC_REPO_URL"; then
                    SOURCE_LABEL="custom"
                    return 0
                fi
                warn "Invalid repository URL. Please enter a full URL such as https://example.com/openbmc.git"
                ;;
            [qQ])
                warn "Source selection cancelled by user."
                exit 2
                ;;
            *)
                warn "Invalid selection: $selection. Please choose 1, 2, or Q."
                ;;
        esac
    done
}

# Capture `source setup` (no args) output, extract available machine names.
list_available_machines() {
    [[ -d "$OPENBMC_DIR/.git" ]] || return 0
    bitbake_env_list_available_machines
}

require_openbmc_repo() {
    if [[ -d "$OPENBMC_DIR/.git" ]]; then
        step_header "Step 2/8: Preparing OpenBMC main repository and resolving machine..."
        info "Main repository already exists at $OPENBMC_DIR — skipping clone."
        verify_source
        return 0
    fi
    info "No OpenBMC main repository found at $OPENBMC_DIR."
    info "A small main repository must be cloned first to list/validate machines (a few minutes)."
    return 3   # repo 未就绪:信号交给调用方(cmd_init)编排 clone_openbmc
}

print_previously_initialized() {
    local -n _mpi_arr="$1"

    local -A _mpi_done=()
    local _mpi_mname _mpi_raw_time _mpi_fmt_time
    while IFS= read -r _mpi_mname; do
        [[ -n "$_mpi_mname" ]] || continue
        _mpi_raw_time=$(machine_state_init_time "$_mpi_mname")
        _mpi_fmt_time=$(format_timestamp "$_mpi_raw_time")
        _mpi_done["$_mpi_mname"]="$_mpi_fmt_time"
    done < <(machine_state_initialized_machines)

    # No init-done machines → nothing to show
    if [[ ${#_mpi_done[@]} -eq 0 ]]; then
        return 0
    fi

    # Print separator
    echo ""
    echo -e "  ${YELLOW}─── Previously initialized ───${NC}"

    # Match init-done machines to their index in the full list
    local _mpi_i=0
    local _mpi_total=${#_mpi_arr[@]}
    local _mpi_idx_width=${#_mpi_total}
    for _mpi_m in "${_mpi_arr[@]}"; do
        _mpi_i=$((_mpi_i + 1))
        if [[ -n "${_mpi_done[$_mpi_m]:-}" ]]; then
            printf "  %${_mpi_idx_width}d) %-20s %s\n" "$_mpi_i" "$_mpi_m" "${_mpi_done[$_mpi_m]}"
        fi
    done
}


