#!/usr/bin/env bash
# lib/repo.sh — 仓库与 machine 解析(require_openbmc_repo/write_source_manifest). 术语见 CONTEXT.md source manifest.
# Exit: direct-exit module（非 leaf-pure, 使用 exit-code 契约值 0/1/2/3）.


read_source_label() {
    local label=""
    if [[ -f "$SOURCE_MANIFEST_FILE" ]]; then
        label=$(read_manifest_field source_label 2>/dev/null || true)
        label=$(trim_whitespace "$label")
    fi
    if [[ -z "$label" ]]; then
        label="community"
    fi
    echo "$label"
}

is_valid_repo_url() {
    local repo_url="$1"
    [[ "$repo_url" =~ ^https?:// ]] || [[ "$repo_url" =~ ^ssh:// ]] || [[ "$repo_url" =~ ^git:// ]] || [[ "$repo_url" =~ ^git@ ]]
}

normalize_repo_url() {
    local repo_url="$1"
    local normalized="$repo_url"
    local host=""
    local path=""

    normalized="${normalized#https://}"
    normalized="${normalized#http://}"
    normalized="${normalized#ssh://}"
    normalized="${normalized#git://}"

    if [[ "$normalized" =~ ^([^@]+)@([^:]+):(.+)$ ]]; then
        host="${BASH_REMATCH[2]}"
        path="${BASH_REMATCH[3]}"
        if [[ "$path" =~ ^([0-9]+)/(.*)$ ]]; then
            normalized="$host/${path#*/}"
        else
            normalized="$host/$path"
        fi
    elif [[ "$normalized" =~ ^([^@]+)@(.+)$ ]]; then
        normalized="${BASH_REMATCH[2]}"
    fi

    if [[ "$normalized" =~ ^\[?([^]/:]+)\]?:(.+)$ ]]; then
        host="${BASH_REMATCH[1]}"
        path="${BASH_REMATCH[2]}"
        if [[ "$path" =~ ^([0-9]+)/(.*)$ ]]; then
            normalized="$host/${path#*/}"
        else
            normalized="$host/$path"
        fi
    fi

    normalized="${normalized%/}"
    normalized="${normalized%.git}"

    if [[ "$normalized" =~ ^([^/]+)/(.*)$ ]]; then
        local host="${BASH_REMATCH[1]}"
        local path="${BASH_REMATCH[2]}"
        host="${host,,}"
        path="${path,,}"
        normalized="$host/$path"
    else
        normalized="${normalized,,}"
    fi

    echo "$normalized"
}

derive_source_label() {
    local normalized

    normalized="$(normalize_repo_url "$OPENBMC_REPO_URL")"
    if [[ "$normalized" == "github.com/openbmc/openbmc" ]]; then
        SOURCE_LABEL="community"
    else
        SOURCE_LABEL="custom"
    fi
}

write_source_manifest() {
    local normalized_source
    local timestamp
    local tmp

    normalized_source="$(normalize_repo_url "$OPENBMC_REPO_URL")"
    timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    derive_source_label

    if [[ "$DRY_RUN" -eq 1 ]]; then
        info "[DRY-RUN] Would write source manifest to $SOURCE_MANIFEST_FILE"
        info "[DRY-RUN]   normalized_source=$normalized_source"
        info "[DRY-RUN]   origin_url=$OPENBMC_REPO_URL"
        info "[DRY-RUN]   source_label=$SOURCE_LABEL"
        return 0
    fi

    mkdir -p "$CONFIGS_DIR"
    tmp=$(mktemp "$CONFIGS_DIR/openbmc-source.manifest.XXXXXX") || return 1

    cat > "$tmp" <<EOF
# openbmc source manifest — auto-generated by 'ob init', do not edit by hand
normalized_source=$normalized_source
origin_url=$OPENBMC_REPO_URL
source_label=$SOURCE_LABEL
created_at=$timestamp
EOF

    if ! mv "$tmp" "$SOURCE_MANIFEST_FILE"; then
        rm -f "$tmp"
        return 1
    fi
}

ensure_bootstrap_local_conf() {
    local local_conf="$BUILD_DIR/conf/local.conf"

    require_path "$local_conf" "local.conf" "Run 'ob init' first." 3

    # Detect GitLab IP for recipes that use ${GITLAB_IP} in SRC_URI.
    # Priority: (1) github-gitlab-url.sh (2) git remote origin URL (3) empty (skip)
    local gitlab_ip=""
    local _rt_script=""
    local _remote_url=""
    for _candidate in "$OPENBMC_DIR"/meta-*/git-mirror-url.sh \
                      "$OPENBMC_DIR"/meta-*/github-gitlab-url.sh; do
        if [[ -f "$_candidate" ]]; then _rt_script="$_candidate"; break; fi
    done
    if [[ -f "$_rt_script" ]]; then
        gitlab_ip=$(grep -oP '^(GITLAB_IP|GIT_MIRROR_HOST)=["'"'"']?\K[^"'"'"'\s]+' "$_rt_script" 2>/dev/null | head -1 || true)
    fi
    if [[ -z "$gitlab_ip" && -f "$OPENBMC_DIR/.git/config" ]]; then
        _remote_url=$(git -C "$OPENBMC_DIR" remote get-url origin 2>/dev/null || true)
        if [[ "$_remote_url" == git@* ]]; then
            gitlab_ip=$(echo "$_remote_url" | sed -E 's/^git@([^:]+):.*/\1/')
        elif [[ "$_remote_url" == http://* || "$_remote_url" == https://* ]]; then
            gitlab_ip=$(echo "$_remote_url" | sed -E 's#^https?://([^/:]+).*#\1#')
        fi
    fi

    # If the remote uses SSH, but recipes reference the host via protocol=https,
    # configure git to rewrite HTTPS URLs to SSH automatically.
    # This handles GitLab servers where HTTPS is unavailable or requires auth
    # that isn't configured in recipes, while SSH key access works out of the box.
    # Only set when missing — user can override manually if needed.
    if [[ -n "$gitlab_ip" ]]; then
        local _existing_rewrite=""
        _existing_rewrite=$(git config --global --get "url.git@${gitlab_ip}:.insteadOf" 2>/dev/null || true)
        if [[ -z "$_existing_rewrite" ]]; then
            git config --global "url.git@${gitlab_ip}:.insteadOf" "https://${gitlab_ip}/"
            info "Configured git insteadOf: https://${gitlab_ip}/ → git@${gitlab_ip} (SSH rewrite for recipe fetches)"
        else
            verbose "Git insteadOf for ${gitlab_ip} already configured: ${_existing_rewrite} → git@${gitlab_ip}:"
        fi
    fi

    # Add include to local.conf if not already present.
    # The .inc file (managed by generate_build_config) contains all ob init settings.
    local include_line="include externalsrc-$MACHINE.inc"

    if grep -qF "$include_line" "$local_conf"; then
        verbose "Include line already exists in local.conf, skipping."
    else
        cp "$local_conf" "${local_conf}.bak.$(date +%Y%m%d%H%M%S)"
        echo "" >> "$local_conf"
        echo "$include_line" >> "$local_conf"
        info "Added '$include_line' to local.conf"
    fi

    verbose "Ensured ob init local.conf settings in $local_conf"
}

verify_source() {
    local lock_source=""
    local current_origin=""
    local current_source=""
    local requested_url="$OPENBMC_REPO_URL"
    local requested_source=""
    local lock_label=""

    if [[ ! -d "$OPENBMC_DIR/.git" ]]; then
        return 0
    fi

    if [[ ! -f "$SOURCE_MANIFEST_FILE" ]]; then
        current_origin=$(git -C "$OPENBMC_DIR" remote get-url origin 2>/dev/null || true)
        if [[ -n "$current_origin" ]]; then
            OPENBMC_REPO_URL="$current_origin"
            SOURCE_LABEL=""
            write_source_manifest
            if [[ -n "$requested_url" ]]; then
                requested_source=$(normalize_repo_url "$requested_url")
                current_source=$(normalize_repo_url "$current_origin")
                if [[ "$requested_source" != "$current_source" ]]; then
                    error "OpenBMC main repository source conflict detected."
                    error "  Current harness source: $current_source"
                    error "  Requested source:       $requested_source"
                    error "A harness may only bind to one OpenBMC main repository source."
                    error "To use a different source, copy ob-harness and run ob init in the new copy."
                    exit 1
                fi
            fi
            OPENBMC_REPO_URL="$requested_url"
        else
            warn "OpenBMC main repository exists but has no origin remote; skipping source lock bootstrap."
        fi
        return 0
    fi

    lock_source=$(read_manifest_field normalized_source || true)
    lock_label=$(read_manifest_field source_label || true)
    current_origin=$(git -C "$OPENBMC_DIR" remote get-url origin 2>/dev/null || true)

    if [[ -n "$current_origin" ]]; then
        current_source=$(normalize_repo_url "$current_origin")
        if [[ -n "$lock_source" ]] && [[ "$current_source" != "$lock_source" ]]; then
            error "OpenBMC main repository source does not match the source manifest."
            error "  Bound source:   $lock_source"
            error "  Actual origin:  $current_source"
            error "Existing openbmc origin and source manifest have drifted, likely due to a manual change."
            error "Please verify the main repository source before continuing. If you need a different source, use a separate harness copy."
            exit 1
        fi
    else
        warn "OpenBMC main repository has no origin remote; skipping lock vs origin verification."
    fi

    if [[ -n "$OPENBMC_REPO_URL" ]]; then
        requested_source=$(normalize_repo_url "$OPENBMC_REPO_URL")
        if [[ -n "$lock_source" ]] && [[ "$requested_source" != "$lock_source" ]]; then
            error "OpenBMC main repository source conflict detected."
            error "  Current harness source: $lock_source${lock_label:+  ($lock_label)}"
            error "  Requested source:       $requested_source"
            error "A harness may only bind to one OpenBMC main repository source."
            error "To use a different source, copy ob-harness and run ob init in the new copy."
            exit 1
        fi
    fi

    return 0
}

select_openbmc_repo_url() {
    if [[ -n "$OPENBMC_REPO_URL" ]]; then
        if ! is_valid_repo_url "$OPENBMC_REPO_URL"; then
            error "Invalid OpenBMC repository URL: $OPENBMC_REPO_URL"
            error "Supported formats: https://, http://, ssh://, git://, git@"
            error "Provide a valid repository URL via --url <url> or OB_OPENBMC_URL, then retry."
            exit 3
        fi
        return 0
    fi

    if [[ -n "${OB_OPENBMC_URL:-}" ]]; then
        OPENBMC_REPO_URL="$OB_OPENBMC_URL"
        if ! is_valid_repo_url "$OPENBMC_REPO_URL"; then
            error "Invalid OpenBMC repository URL from OB_OPENBMC_URL: $OPENBMC_REPO_URL"
            error "Set OB_OPENBMC_URL to a valid URL, or rerun 'ob init' interactively."
            exit 3
        fi
        return 0
    fi

    while true; do
        echo ""
        echo "Select the OpenBMC source repository:"
        echo "  1) Community (https://github.com/openbmc/openbmc.git)"
        echo "  2) Custom repository URL"
        echo "  Q) Quit source selection (q/Q)"
        if ! read -r -p "$(echo -e "${PROMPT_PREFIX} Choose [1/2/Q]: ")" selection; then
            error "Unable to read repository source selection from stdin."
            error "Use --url <url> or set OB_OPENBMC_URL in non-interactive mode."
            exit 3
        fi

        case "$selection" in
            1)
                OPENBMC_REPO_URL="$DEFAULT_OPENBMC_REPO_URL"
                SOURCE_LABEL="community"
                return 0
                ;;
            2)
                if ! read -r -p "$(echo -e "${PROMPT_PREFIX} Enter the full repository URL: ")" OPENBMC_REPO_URL; then
                    error "Unable to read custom repository URL from stdin."
                    error "Use --url <url> or set OB_OPENBMC_URL in non-interactive mode."
                    exit 3
                fi
                if [[ -z "$OPENBMC_REPO_URL" ]]; then
                    info "Returning to source selection."
                    continue
                fi
                if is_valid_repo_url "$OPENBMC_REPO_URL"; then
                    SOURCE_LABEL="custom"
                    return 0
                fi
                warn "Invalid repository URL. Please enter a full URL such as https://example.com/openbmc.git"
                ;;
            [qQ])
                warn "Source selection cancelled by user."
                exit 2
                ;;
            *)
                warn "Invalid selection: $selection. Please choose 1, 2, or Q."
                ;;
        esac
    done
}

# Capture `source setup` (no args) output, extract available machine names.
list_available_machines() {
    [[ -d "$OPENBMC_DIR/.git" ]] || return 0
    bitbake_env_list_available_machines
}

# Print supported machine list (passthrough for readability)
print_available_machines() {
    local machines
    machines=$(list_available_machines)
    if [[ -z "$machines" ]]; then
        warn "No machines found. The OpenBMC main repository may be incomplete."
        warn "Try updating it: cd $OPENBMC_DIR && git pull"
        return 0
    fi
    info "Available machines in this repository:"
    local term_cols
    term_cols=$(tput cols 2>/dev/null) || term_cols=80
    echo "$machines" | column -c "$term_cols" 2>/dev/null || echo "$machines"
}

require_openbmc_repo() {
    if [[ -d "$OPENBMC_DIR/.git" ]]; then
        step_header "Step 2/8: Preparing OpenBMC main repository and resolving machine..."
        info "Main repository already exists at $OPENBMC_DIR — skipping clone."
        verify_source
        return 0
    fi
    info "No OpenBMC main repository found at $OPENBMC_DIR."
    info "A small main repository must be cloned first to list/validate machines (a few minutes)."
    return 3   # repo 未就绪:信号交给调用方(cmd_init)编排 clone_openbmc
}

print_previously_initialized() {
    local -n _mpi_arr="$1"

    local -A _mpi_done=()
    local _mpi_mname _mpi_raw_time _mpi_fmt_time
    while IFS= read -r _mpi_mname; do
        [[ -n "$_mpi_mname" ]] || continue
        _mpi_raw_time=$(machine_state_init_time "$_mpi_mname")
        _mpi_fmt_time=$(format_timestamp "$_mpi_raw_time")
        _mpi_done["$_mpi_mname"]="$_mpi_fmt_time"
    done < <(machine_state_initialized_machines)

    # No init-done machines → nothing to show
    if [[ ${#_mpi_done[@]} -eq 0 ]]; then
        return 0
    fi

    # Print separator
    echo ""
    echo -e "  ${YELLOW}─── Previously initialized ───${NC}"

    # Match init-done machines to their index in the full list
    local _mpi_i=0
    local _mpi_total=${#_mpi_arr[@]}
    local _mpi_idx_width=${#_mpi_total}
    for _mpi_m in "${_mpi_arr[@]}"; do
        _mpi_i=$((_mpi_i + 1))
        if [[ -n "${_mpi_done[$_mpi_m]:-}" ]]; then
            printf "  %${_mpi_idx_width}d) %-20s %s\n" "$_mpi_i" "$_mpi_m" "${_mpi_done[$_mpi_m]}"
        fi
    done
}

resolve_machine() {
    local machines
    machines=$(list_available_machines)

    # Build numbered machine list
    local -a machine_arr=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && machine_arr+=("$line")
    done <<< "$machines"

    # Fast path: machine specified and valid
    if [[ -n "$MACHINE" ]] && echo "$machines" | grep -qx -- "$MACHINE"; then
        print_available_machines
        print_previously_initialized machine_arr
        info "Machine '$MACHINE' confirmed."
        return 0
    fi

    if [[ -n "$MACHINE" ]]; then
        warn "Machine '$MACHINE' is not in the available list."
    else
        warn "No machine specified."
    fi

    if [[ ! -t 0 ]]; then
        error "No valid machine and no interactive terminal. Pass a valid machine: ob init <machine>"
        exit 3
    fi

    # Print numbered list in columns (adapt to terminal width)
    info "Available machines (enter number or name):"
    local total=${#machine_arr[@]}
    local idx_width=${#total}
    local term_cols
    term_cols=$(tput cols 2>/dev/null) || term_cols=80
    local i=0
    {
        for m in "${machine_arr[@]}"; do
            i=$((i + 1))
            printf "  %${idx_width}d) %s\n" "$i" "$m"
        done
    } | column -c "$term_cols" 2>/dev/null

    print_previously_initialized machine_arr

    local selected
    local chosen=""
    while true; do
        if ! read -r -p "$(echo -e "${PROMPT_PREFIX} Select a machine [1-${#machine_arr[@]}] or type machine name (0 to cancel): ")" selected; then
            error "Unable to read machine selection from stdin."
            exit 1
        fi
        if [[ "$selected" == "0" ]]; then
            warn "Init cancelled by user."
            exit 2
        fi
        # Try as number first
        if [[ "$selected" =~ ^[0-9]+$ ]]; then
            if [[ "$selected" -ge 1 && "$selected" -le "${#machine_arr[@]}" ]]; then
                chosen="${machine_arr[$((selected - 1))]}"
                MACHINE="$chosen"
                break
            fi
            warn "Number out of range (1-${#machine_arr[@]}): $selected"
            continue
        fi
        # Try as name
        if echo "$machines" | grep -qx -- "$selected"; then
            MACHINE="$selected"
            break
        fi
        warn "Invalid machine: $selected"
    done

    # === Post-selection confirmation (same pattern as cmd_build) ===
    echo ""
    info "Machine '$MACHINE' selected."
    echo ""
    local ca_rc=0
    confirm_action "init" "$MACHINE" || ca_rc=$?
    if [[ "$ca_rc" -eq 2 ]]; then
        warn "Init cancelled by user."
        exit 2
    elif [[ "$ca_rc" -ne 0 ]]; then
        exit 1
    fi
    echo ""
    info "Init confirmed for machine '$MACHINE'."
    return 0
}

